// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZoZu7MGYfJ2-wuxL1Rp5D-xlV5sfisms',
    appId: '1:1061899021148:web:a6ca1bca2e1c26b20fef99',
    messagingSenderId: '1061899021148',
    projectId: 'allone-409417',
    authDomain: 'allone-409417.firebaseapp.com',
    databaseURL: 'https://allone-409417-default-rtdb.firebaseio.com',
    storageBucket: 'allone-409417.appspot.com',
    measurementId: 'G-74C155QD7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1kYwoRh9Q5gWYCERmIC6e-UiWB9q7TZ4',
    appId: '1:1061899021148:android:96a3685642292f7c0fef99',
    messagingSenderId: '1061899021148',
    projectId: 'allone-409417',
    databaseURL: 'https://allone-409417-default-rtdb.firebaseio.com',
    storageBucket: 'allone-409417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcgkb7zHps4-SPZgmFanb5v83rQjJAwdI',
    appId: '1:1061899021148:ios:91f025fe74aba7650fef99',
    messagingSenderId: '1061899021148',
    projectId: 'allone-409417',
    databaseURL: 'https://allone-409417-default-rtdb.firebaseio.com',
    storageBucket: 'allone-409417.appspot.com',
    androidClientId: '1061899021148-63sqhdv1kkok6dm76qqqpvcoagj954ac.apps.googleusercontent.com',
    iosClientId: '1061899021148-36aej1l8b8iqb7ipr9hesnqre40qmtkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.allOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcgkb7zHps4-SPZgmFanb5v83rQjJAwdI',
    appId: '1:1061899021148:ios:38fb905125dbb89d0fef99',
    messagingSenderId: '1061899021148',
    projectId: 'allone-409417',
    databaseURL: 'https://allone-409417-default-rtdb.firebaseio.com',
    storageBucket: 'allone-409417.appspot.com',
    androidClientId: '1061899021148-63sqhdv1kkok6dm76qqqpvcoagj954ac.apps.googleusercontent.com',
    iosClientId: '1061899021148-8cg5htppe6q6mph53tn03cvnsksi04g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.allOne.RunnerTests',
  );
}
